site_name: Plural Respect
site_url: https://pluralrespect.neocities.org
site_description: A crash course in plurality for systems and singlets alike.
#copyright: CC-BY-SA 4.0 International

nav:
  - Foreword: index.md
  - Shattering Expectations: expectations.md
  - Facing Challenges: challenges.md
  - Gaining Familiarity: familiarity.md
  - Afterword: afterword.md
  - "Self-Respect: The Fictive": fictive.md

theme: windmill

extra_css:
    - css/theme-adjustments.css

extra:
  version: 2.0.0
  logo: img/custom-journey-flag.png
  article_nav_top: false
