site_name: A System's Guide
site_url: https://sys.guide
site_description: An informal handbook for systems and their aspiring friends.
#copyright: CC-BY-SA 4.0 International

nav:
  - Foreword: index.md
  - Establishing Foundations: foundations.md
  - Shattering Expectations: expectations.md
  - Facing Challenges: challenges.md
  - Gaining Familiarity: familiarity.md
  - Afterword: afterword.md
  - "Addendum: Affordances": affordances.md
  - "Addendum: The Fictive": fictive.md
  - "Addendum: Plural-Asexuality": asexuality.md
  - "Letters: Am I Plural?": letters.md
  - "Addendum: Calibration": calibration.md
  - "Addendum: On Shorthanding": calibration.md

theme:
  name: windmill
  custom_dir: custom/

extra_css:
    - css/theme-adjustments.css

extra:
  version: 2.6
  logo: img/custom-journey-flag.png
  article_nav_top: false
